### ISSUE TITLE
Enable RTMP push to youtube / twitch / etc

### ISSUE THREAD

**Issue by JasonRivers** [JasonRivers/Docker-nginx-rtmp#4]
We need an option when starting the container to enable pushing the stream to youtube / twitch / etc.

**Comment by schmic** [comment]
Does not work for me when pushing to Twitch.

```
nginx-rtmp | nginx: [emerg] invalid port in url "https://twitch.tv/th...." in /opt/nginx/conf/nginx.conf:56
```

My docker-compose.yml:
```
version: "2"
services:
  nginx:
    image: jasonrivers/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - 1935:1935
      - 8081:8080
    environment: 
      - "RTMP_STREAM_NAMES=twitch,app,dadaurka"
      - "RTMP_PUSH_URLS=https://twitch.tv/XXX/YYY"
```
